#!/bin/bash

while getopts 'v:h' flag 
do
    case "${flag}" in
        v) 
            version=${OPTARG}
            ;;
        h)
            echo "script usage: ./build [-v]"
            exit 1
            ;;
        \?)
            echo "script usage: ./build [-v]" >&2
            exit 1
            ;;
    esac
done

if [[ $version == "" ]]
then
    echo "script usage: ./build [-v]"
    exit 1
fi

package="swob-gateway-client"
release="1"
maintainer="Promise <promisefru1@gmail.com>"
description="smswithoutborders gateway client"

BUILD_DIR="${package}_${version}-${release}"
INSTALL_DIR="${BUILD_DIR}/usr/share/${BUILD_DIR}"

repository="https://github.com/smswithoutborders/SMSWithoutBorders-Gateway-Client.git"
release_branch="alpha"
size="48000"

echo "[!] creating build directory ${BUILD_DIR} ..." 
mkdir $BUILD_DIR && \
echo "[+] success" 

#logger
LOG_FILE=$BUILD_DIR/build.log
exec > >(tee -a ${LOG_FILE}) 2>&1

# create build directory
echo "[!] creating installation directory ${INSTALL_DIR} ..." 
mkdir -p $INSTALL_DIR && \
echo "[+] success" 

# clone project
echo "[!] cloning ${repository} ..." 
echo "[!] this may take a while please wait ..." 
git clone $repository $INSTALL_DIR --branch $release_branch && \
echo "[+] success" 

# create DEBIAN files
echo "[!] creating DEBIAN directory in ${BUILD_DIR} ..." 
mkdir -p $BUILD_DIR/DEBIAN && \
echo "[+] success" 

# create control file
echo "[!] creating control file in ${BUILD_DIR}/DEBIAN ..." 

echo "Package: ${package}
Version: ${version}-${release}
Priority: optional
Architecture: all
Depends: python3
Installed-Size: $size
Maintainer: $maintainer
Description: $description" > $BUILD_DIR/DEBIAN/control && \
echo "[+] success" 

# create postinst file
echo "[!] creating postinst file in ${BUILD_DIR}/DEBIAN ..." 

echo "#!/bin/bash

cd usr/share/${BUILD_DIR}
make 
make install
make start
make enable
echo \"Successfully installed ${package}\"" > $BUILD_DIR/DEBIAN/postinst && \
echo "[+] success" 

# create prerm file
echo "[!] creating prerm file in ${BUILD_DIR}/DEBIAN ..." 

echo "#!/bin/bash

cd usr/share/${BUILD_DIR}
make fuckit
rm -rf src/
rm -rf .git/
rm -rf .configs/
rm -rf third_party/
rm -rf venv/
echo \"Successfully removed ${package}\"" > $BUILD_DIR/DEBIAN/prerm && \
echo "[+] success" 

# change scripts permissions to 0755
echo "[!] changing postinst file permissions to 0755 ..." 
chmod 0755 $BUILD_DIR/DEBIAN/postinst && \
echo "[+] success" 

echo "[!] changing prerm file permissions to 0755 ..." 
chmod 0755 $BUILD_DIR/DEBIAN/prerm && \
echo "[+] success" 

# build .deb format
echo "[!] building ${BUILD_DIR}.deb file in ${PWD} ..." 
dpkg-deb --build $BUILD_DIR && \
echo "[+] success" 
